basePath: /api/v1
definitions:
  model.Response:
    properties:
      code:
        type: integer
      count:
        type: integer
      count_all:
        type: integer
      data: {}
      limit:
        type: integer
      message:
        type: string
      next_page:
        type: integer
      page:
        type: integer
      previous_page:
        type: integer
      total_page:
        type: integer
    type: object
  model.TaskRequest:
    properties:
      description:
        type: string
      status:
        type: integer
      title:
        type: string
    type: object
  model.TaskUpdateRequest:
    properties:
      description:
        type: string
      status:
        type: integer
      title:
        type: string
    type: object
  model.TaskUpdateStatusRequest:
    properties:
      status:
        type: integer
    type: object
host: localhost:5555
info:
  contact: {}
  description: This is a description of Task Management API
  title: Task Management API
  version: "1.0"
paths:
  /task:
    get:
      description: List tasks
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                result:
                  $ref: '#/definitions/model.Response'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
      summary: List tasks
      tags:
      - task
    post:
      description: Create task
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Create task
        in: body
        name: taskRequest
        required: true
        schema:
          $ref: '#/definitions/model.TaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                result:
                  $ref: '#/definitions/model.Response'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
      summary: Create task
      tags:
      - task
  /task/{id}:
    delete:
      description: Delete task by id
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: task id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                result:
                  $ref: '#/definitions/model.Response'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
      summary: Delete task by id
      tags:
      - task
    get:
      description: Get one task
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: task id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                result:
                  $ref: '#/definitions/model.Response'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
      summary: Get one task
      tags:
      - task
    put:
      description: Update task
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: user uuid
        in: path
        name: id
        required: true
        type: string
      - description: Update task
        in: body
        name: taskUpdateRequest
        required: true
        schema:
          $ref: '#/definitions/model.TaskUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                result:
                  $ref: '#/definitions/model.Response'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
      summary: Update task
      tags:
      - task
  /task/{id}/status:
    put:
      description: Update status
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: user uuid
        in: path
        name: id
        required: true
        type: string
      - description: Update User status
        in: body
        name: taskUpdateStatusRequest
        required: true
        schema:
          $ref: '#/definitions/model.TaskUpdateStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                result:
                  $ref: '#/definitions/model.Response'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                error:
                  $ref: '#/definitions/model.Response'
              type: object
      summary: Update status
      tags:
      - task
swagger: "2.0"
